name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'  # Cache npm dependencies

      # Step 3: Install dependencies in the 'my-app' directory
      - name: Install dependencies
        run: npm install
        working-directory: ./my-app  # Specify the correct directory

      # Step 4: Run tests in the 'my-app' directory
      - name: Run tests
        run: npm test
        working-directory: ./my-app  # Specify the correct directory

      # Step 5: Build the app (optional)
      - name: Build app
        run: npm run build
        working-directory: ./my-app  # Specify the correct directory
